network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s1:
      dhcp4: false
      addresses:
        - 192.168.64.3/24
      routes:
        - to: default
          via: 192.168.64.1
      nameservers:
        addresses:
          - 127.0.0.53
